# hosts/nixbox/configuration.nix
# System-level config for the Intel desktop machine.
# hardware-configuration.nix is generated by nixos-generate-config during install
# and should live alongside this file. Do NOT edit it by hand.
{ config, lib, pkgs, ... }:

{
  imports = [ ./hardware-configuration.nix ];

  # ── Boot ──────────────────────────────────────────────────────────────
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # ── Network ───────────────────────────────────────────────────────────
  networking.hostName = "nixbox";
  networking.networkmanager.enable = true;

  # ── Locale & timezone ─────────────────────────────────────────────────
  time.timeZone = "Asia/Jerusalem";
  i18n.defaultLocale = "en_US.UTF-8";

  # ── Intel iGPU — hardware acceleration ────────────────────────────────
  # Works on Broadwell (2014) and newer Intel graphics.
  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver   # VA-API (iHD) — modern Intel
      intel-vaapi-driver   # VA-API (i965) — better browser compat
      libvdpau-va-gl
    ];
  };
  environment.sessionVariables = {
    LIBVA_DRIVER_NAME = "iHD";
  };

  # ── Hyprland ──────────────────────────────────────────────────────────
  programs.hyprland = {
    enable = true;
    xwayland.enable = true;
  };

  # uwsm — Universal Wayland Session Manager.
  # Wraps Hyprland in a proper systemd user session so greetd can launch
  # it without triggering the "not designed to be launched by a DM" warning.
  # Hyprland ships a hyprland-uwsm.desktop for exactly this purpose.
  programs.uwsm = {
    enable = true;
    waylandCompositors.hyprland = {
      prettyName = "Hyprland";
      comment     = "Hyprland via uwsm";
      binPath     = "/run/current-system/sw/bin/Hyprland";
    };
  };

  # ── Display manager: greetd + tuigreet ───────────────────────────────
  # tuigreet hands off to uwsm, which starts Hyprland inside a clean
  # systemd user session — no DM-launch warning, password on boot.
  services.greetd = {
    enable = true;
    settings = {
      default_session = {
        command = "${pkgs.tuigreet}/bin/tuigreet --time --remember --cmd 'uwsm start hyprland-uwsm.desktop'";
        user = "greeter";
      };
    };
  };
  # Silence TTY output noise on greetd startup
  systemd.services.greetd.serviceConfig = {
    Type             = "idle";
    StandardInput    = "tty";
    StandardOutput   = "tty";
    StandardError    = "journal";
    TTYReset         = true;
    TTYVHangup       = true;
    TTYVTDisallocate = true;
  };

  # ── XDG portal (screen sharing, file pickers) ─────────────────────────
  xdg.portal = {
    enable = true;
    extraPortals = [ pkgs.xdg-desktop-portal-hyprland ];
  };

  # ── Audio: pipewire ───────────────────────────────────────────────────
  services.pipewire = {
    enable            = true;
    alsa.enable       = true;
    alsa.support32Bit = true;
    pulse.enable      = true;
  };
  services.pulseaudio.enable = false; # replaced by pipewire
  security.rtkit.enable = true;

  # ── Bluetooth ─────────────────────────────────────────────────────────
  # blueman provides a tray applet + GUI manager (blueman-applet).
  # hardware.bluetooth.powerOnBoot keeps the adapter on across reboots.
  hardware.bluetooth = {
    enable        = true;
    powerOnBoot   = true;
  };
  services.blueman.enable = true;   # DBus service + blueman-applet

  # ── Polkit (Hyprland privilege escalation) ────────────────────────────
  security.polkit.enable = true;

  # ── Podman ────────────────────────────────────────────────────────────
  virtualisation.podman = {
    enable = true;
    dockerCompat = true;          # type 'docker', get podman
    defaultNetwork.settings.dns_enabled = true;
    autoPrune = {
      enable = true;
      dates  = "weekly";
    };
  };

  # ── User ──────────────────────────────────────────────────────────────
  users.users.gl = {
    isNormalUser = true;
    extraGroups  = [ "wheel" "networkmanager" "video" "audio" "podman" ];
    shell        = pkgs.bash; # login shell is bash; nushell launched interactively
  };

  # ── Unfree packages (firmware, etc.) ──────────────────────────────────
  nixpkgs.config.allowUnfree = true;

  # ── System-level packages (keep this minimal) ─────────────────────────
  environment.systemPackages = with pkgs; [
    git
    vim
    wget
    curl
    pciutils   # lspci — GPU diagnostics
    usbutils
    claude-code
    gh         # GitHub CLI
    glab       # GitLab CLI
  ];

  # ── Fonts ─────────────────────────────────────────────────────────────
  fonts.packages = with pkgs; [
    nerd-fonts.jetbrains-mono
    nerd-fonts.fira-code
    noto-fonts
    noto-fonts-color-emoji
  ];
  # RGB subpixel rendering sharpens text significantly on LCD/LED panels.
  # medium hinting gives crisper UI text than the default "slight".
  fonts.fontconfig = {
    subpixel.rgba  = "rgb";
    hinting.style  = "medium";
  };

  # ── Nix settings ──────────────────────────────────────────────────────
  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    auto-optimise-store   = true;
  };

  # Automatic garbage collection (mirrors the manual `gcold` alias)
  nix.gc = {
    automatic = true;
    dates     = "weekly";
    options   = "--delete-older-than 14d";
  };

  system.stateVersion = "25.05"; # DO NOT change after install
}
