# hosts/nixbox/configuration.nix
# System-level config for the Intel desktop machine.
# hardware-configuration.nix is generated by nixos-generate-config during install
# and should live alongside this file. Do NOT edit it by hand.
{ config, lib, pkgs, ... }:

{
  imports = [ ./hardware-configuration.nix ];

  # ── Boot ──────────────────────────────────────────────────────────────
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # ── Network ───────────────────────────────────────────────────────────
  networking.hostName = "nixbox";
  networking.networkmanager.enable = true;

  # ── Locale & timezone ─────────────────────────────────────────────────
  time.timeZone = "Asia/Jerusalem";
  i18n.defaultLocale = "en_US.UTF-8";

  # ── Intel iGPU — hardware acceleration ────────────────────────────────
  # Works on Broadwell (2014) and newer Intel graphics.
  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver   # VA-API (iHD) — modern Intel
      intel-vaapi-driver   # VA-API (i965) — better browser compat
      libvdpau-va-gl
    ];
  };
  environment.sessionVariables = {
    LIBVA_DRIVER_NAME = "iHD";
  };

  # ── Display manager: SDDM (Wayland) ──────────────────────────────────
  services.displayManager.sddm = {
    enable = true;
    wayland.enable = true;
  };

  # ── Desktop: Hyprland ────────────────────────────────────────────────
  # Registers hyprland.desktop session entry so SDDM can offer it.
  programs.hyprland.enable = true;

  # uwsm wraps Hyprland in a proper systemd user session (XDG activation,
  # D-Bus scoping, clean teardown). Side-effect: switches dbus.implementation
  # to "broker" — first activation MUST use nixos-rebuild boot, not switch.
  programs.uwsm = {
    enable = true;
    waylandCompositors.hyprland = {
      prettyName = "Hyprland";
      comment     = "Hyprland compositor managed by uwsm";
      binPath     = "/run/current-system/sw/bin/Hyprland";
    };
  };

  # ── Chrome: Catppuccin Mocha theme via system policy ─────────────────
  # programs.chromium writes to /etc/opt/chrome/policies/managed/ which
  # Google Chrome reads on startup (unlike home-manager extensions which
  # only work with open-source Chromium). The Mocha theme ID is the stable
  # Chrome Web Store ID for catppuccin/chrome.
  programs.chromium = {
    enable = true;
    extensions = [
      "bkkmolkhemgaeaeggcmfbghljjjoofoh" # Catppuccin Mocha Chrome theme
    ];
  };

  # ── Audio: pipewire ───────────────────────────────────────────────────
  services.pipewire = {
    enable            = true;
    alsa.enable       = true;
    alsa.support32Bit = true;
    pulse.enable      = true;
  };
  services.pulseaudio.enable = false; # replaced by pipewire
  security.rtkit.enable = true;

  # ── Bluetooth ─────────────────────────────────────────────────────────
  # bluetui (home.packages in gui.nix) is the TUI manager via BlueZ D-Bus.
  # blueman disabled — bluetui replaces it; no tray applet needed.
  hardware.bluetooth = {
    enable        = true;
    powerOnBoot   = true;
  };
  services.blueman.enable = false;  # replaced by bluetui TUI

  # ── Polkit (Hyprland privilege escalation) ────────────────────────────
  security.polkit.enable = true;

  # ── Podman ────────────────────────────────────────────────────────────
  virtualisation.podman = {
    enable = true;
    dockerCompat = true;          # type 'docker', get podman
    defaultNetwork.settings.dns_enabled = true;
    autoPrune = {
      enable = true;
      dates  = "weekly";
    };
  };

  # ── User ──────────────────────────────────────────────────────────────
  users.users.gl = {
    isNormalUser = true;
    extraGroups  = [ "wheel" "networkmanager" "video" "audio" "podman" ];
    shell        = pkgs.bash; # login shell is bash; nushell launched interactively
  };

  # ── Unfree packages (firmware, etc.) ──────────────────────────────────
  nixpkgs.config.allowUnfree = true;

  # ── System-level packages (keep this minimal) ─────────────────────────
  environment.systemPackages = with pkgs; [
    git
    vim
    wget
    curl
    pciutils   # lspci — GPU diagnostics
    usbutils
    claude-code
    gh
  ];

  # ── Fonts ─────────────────────────────────────────────────────────────
  fonts.packages = with pkgs; [
    nerd-fonts.jetbrains-mono
    nerd-fonts.fira-code
    noto-fonts
    noto-fonts-color-emoji
  ];
  # RGB subpixel rendering sharpens text significantly on LCD/LED panels.
  # medium hinting gives crisper UI text than the default "slight".
  fonts.fontconfig = {
    subpixel.rgba  = "rgb";
    hinting.style  = "medium";
  };

  # ── Nix settings ──────────────────────────────────────────────────────
  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    auto-optimise-store   = true;
  };

  # Automatic garbage collection (mirrors the manual `gcold` alias)
  nix.gc = {
    automatic = true;
    dates     = "weekly";
    options   = "--delete-older-than 14d";
  };

  system.stateVersion = "25.05"; # DO NOT change after install
}
