# hosts/nixbox/configuration.nix
# System-level config for the Intel desktop machine.
# hardware-configuration.nix is generated by nixos-generate-config during install
# and should live alongside this file. Do NOT edit it by hand.
{ config, lib, pkgs, ... }:

{
  imports = [ ./hardware-configuration.nix ];

  # ── Boot ──────────────────────────────────────────────────────────────
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # ── Network ───────────────────────────────────────────────────────────
  networking.hostName = "nixbox"; # change to whatever you want
  networking.networkmanager.enable = true;

  # ── Locale & timezone ─────────────────────────────────────────────────
  time.timeZone = "Asia/Jerusalem";
  i18n.defaultLocale = "en_US.UTF-8";

  # ── Intel iGPU — hardware acceleration ────────────────────────────────
  # Works on Broadwell (2014) and newer Intel graphics.
  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver   # VA-API (iHD) — modern Intel
      intel-vaapi-driver   # VA-API (i965) — better browser compat
      libvdpau-va-gl
    ];
  };
  environment.sessionVariables = {
    LIBVA_DRIVER_NAME = "iHD";
  };

  # ── Hyprland ──────────────────────────────────────────────────────────
  programs.hyprland = {
    enable = true;
    xwayland.enable = true;
  };

  # ── Display manager: greetd + tuigreet ────────────────────────────────
  services.greetd = {
    enable = true;
    settings = {
      default_session = {
        command = "${pkgs.greetd.tuigreet}/bin/tuigreet --time --cmd Hyprland";
        user = "greeter";
      };
    };
  };
  # Silence TTY output noise on greetd startup
  systemd.services.greetd.serviceConfig = {
    Type             = "idle";
    StandardInput    = "tty";
    StandardOutput   = "tty";
    StandardError    = "journal";
    TTYReset         = true;
    TTYVHangup       = true;
    TTYVTDisallocate = true;
  };

  # ── XDG portal (screen sharing, file pickers) ─────────────────────────
  xdg.portal = {
    enable = true;
    extraPortals = [ pkgs.xdg-desktop-portal-hyprland ];
  };

  # ── Audio: pipewire ───────────────────────────────────────────────────
  services.pipewire = {
    enable          = true;
    alsa.enable     = true;
    alsa.support32Bit = true;
    pulse.enable    = true;
  };
  hardware.pulseaudio.enable = false; # replaced by pipewire
  security.rtkit.enable = true;

  # ── Polkit (Hyprland privilege escalation) ────────────────────────────
  security.polkit.enable = true;

  # ── Podman ────────────────────────────────────────────────────────────
  virtualisation.podman = {
    enable = true;
    dockerCompat = true; # type 'docker', get podman
    defaultNetwork.settings.dns_enabled = true;
  };

  # ── User ──────────────────────────────────────────────────────────────
  users.users.gl = {
    isNormalUser = true;
    extraGroups  = [ "wheel" "networkmanager" "video" "audio" "podman" ];
    shell        = pkgs.bash; # login shell is bash; nushell launched interactively
  };

  # ── Unfree packages (firmware, etc.) ──────────────────────────────────
  nixpkgs.config.allowUnfree = true;

  # ── System-level packages (keep this minimal) ─────────────────────────
  environment.systemPackages = with pkgs; [
    git
    vim
    wget
    curl
    pciutils   # lspci — GPU diagnostics
    usbutils
  ];

  # ── Fonts ─────────────────────────────────────────────────────────────
  fonts.packages = with pkgs; [
    nerd-fonts.jetbrains-mono
    nerd-fonts.fira-code
    noto-fonts
    noto-fonts-color-emoji
  ];

  # ── Nix settings ──────────────────────────────────────────────────────
  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    auto-optimise-store   = true;
  };

  system.stateVersion = "25.05"; # DO NOT change after install
}
